-- MySQL Script generated by MySQL Workbench
-- 08/23/15 13:47:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Your_Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Your_Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Your_Database` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Your_Database` ;

-- -----------------------------------------------------
-- Table `Your_Database`.`Match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Match` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Match` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `mapId` INT NULL COMMENT '',
  `matchCreation` DOUBLE NULL COMMENT '',
  `matchDuration` DOUBLE NULL COMMENT '',
  `matchId` DOUBLE NULL COMMENT '',
  `matchMode` VARCHAR(45) NULL COMMENT '',
  `matchType` VARCHAR(45) NULL COMMENT '',
  `matchVersion` VARCHAR(45) NULL COMMENT '',
  `platformId` VARCHAR(45) NULL COMMENT '',
  `queueType` VARCHAR(45) NULL COMMENT '',
  `region` VARCHAR(45) NULL COMMENT '',
  `season` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Participant` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Participant` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `championId` INT NULL COMMENT '',
  `highestAchievedSeasonTier` VARCHAR(45) NULL COMMENT '',
  `participantId` INT NULL COMMENT '',
  `spell1Id` INT NULL COMMENT '',
  `spell2Id` INT NULL COMMENT '',
  `teamId` INT NULL COMMENT '',
  `matchId` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Team` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Team` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `baronKills` INT NULL COMMENT '',
  `dominionVictoryScore` DOUBLE NULL COMMENT '',
  `dragonKills` INT NULL COMMENT '',
  `firstBaron` TINYINT(1) NULL COMMENT '',
  `firstBlood` TINYINT(1) NULL COMMENT '',
  `firstDragon` TINYINT(1) NULL COMMENT '',
  `firstInhibitor` TINYINT(1) NULL COMMENT '',
  `firstTower` TINYINT(1) NULL COMMENT '',
  `inhibitorKills` INT NULL COMMENT '',
  `teamId` INT NULL COMMENT '',
  `towerKills` INT NULL COMMENT '',
  `vilemawKills` INT NULL COMMENT '',
  `winner` TINYINT(1) NULL COMMENT '',
  `matchId` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Mastery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Mastery` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Mastery` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `masteryId` DOUBLE NULL COMMENT '',
  `rank` DOUBLE NULL COMMENT '',
  `participantId` INT NULL COMMENT '',
  `matchId` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Rune`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Rune` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Rune` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `rank` DOUBLE NULL COMMENT '',
  `runeId` DOUBLE NULL COMMENT '',
  `participantId` INT NULL COMMENT '',
  `matchId` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Player` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Player` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `matchHistoryUri` VARCHAR(45) NULL COMMENT '',
  `profileIcon` INT NULL COMMENT '',
  `summonerId` DOUBLE NULL COMMENT '',
  `summonerName` VARCHAR(45) NULL COMMENT '',
  `participantId` INT NULL COMMENT '',
  `matchId` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`BannedChampion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`BannedChampion` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`BannedChampion` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `championId` INT NULL COMMENT '',
  `pickTurn` INT NULL COMMENT '',
  `teamId` INT NULL COMMENT '',
  `matchId` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`ParticipantStats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`ParticipantStats` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`ParticipantStats` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `assists` DOUBLE NULL COMMENT '',
  `champLevel` DOUBLE NULL COMMENT '',
  `combatPlayerScore` DOUBLE NULL COMMENT '',
  `deaths` DOUBLE NULL COMMENT '',
  `doubleKills` DOUBLE NULL COMMENT '',
  `firstBloodAssist` TINYINT(1) NULL COMMENT '',
  `firstBloodKill` TINYINT(1) NULL COMMENT '',
  `firstInhibitorAssist` TINYINT(1) NULL COMMENT '',
  `firstInhibitorKill` TINYINT(1) NULL COMMENT '',
  `firstTowerAssist` TINYINT(1) NULL COMMENT '',
  `firstTowerKill` TINYINT(1) NULL COMMENT '',
  `goldEarned` DOUBLE NULL COMMENT '',
  `goldSpent` DOUBLE NULL COMMENT '',
  `inhibitorKills` DOUBLE NULL COMMENT '',
  `item0` DOUBLE NULL COMMENT '',
  `item1` DOUBLE NULL COMMENT '',
  `item2` DOUBLE NULL COMMENT '',
  `item3` DOUBLE NULL COMMENT '',
  `item4` DOUBLE NULL COMMENT '',
  `item5` DOUBLE NULL COMMENT '',
  `item6` DOUBLE NULL COMMENT '',
  `killingSprees` DOUBLE NULL COMMENT '',
  `kills` DOUBLE NULL COMMENT '',
  `largestCriticalStrike` DOUBLE NULL COMMENT '',
  `largestKillingSpree` DOUBLE NULL COMMENT '',
  `largestMultiKill` DOUBLE NULL COMMENT '',
  `magicDamageDealt` DOUBLE NULL COMMENT '',
  `magicDamageDealtToChampions` DOUBLE NULL COMMENT '',
  `magicDamageTaken` DOUBLE NULL COMMENT '',
  `minionsKilled` DOUBLE NULL COMMENT '',
  `neutralMinionsKilled` DOUBLE NULL COMMENT '',
  `neutralMinionsKilledEnemyJungle` DOUBLE NULL COMMENT '',
  `neutralMinionsKilledTeamJungle` DOUBLE NULL COMMENT '',
  `nodeCapture` DOUBLE NULL COMMENT '',
  `nodeCaptureAssist` DOUBLE NULL COMMENT '',
  `nodeNeutralize` DOUBLE NULL COMMENT '',
  `nodeNeutralizeAssist` DOUBLE NULL COMMENT '',
  `objectivePlayerScore` DOUBLE NULL COMMENT '',
  `pentaKills` DOUBLE NULL COMMENT '',
  `physicalDamageDealt` DOUBLE NULL COMMENT '',
  `physicalDamageDealtToChampions` DOUBLE NULL COMMENT '',
  `physicalDamageTaken` DOUBLE NULL COMMENT '',
  `quadraKills` DOUBLE NULL COMMENT '',
  `sightWardsBoughtInGame` DOUBLE NULL COMMENT '',
  `teamObjective` DOUBLE NULL COMMENT '',
  `totalDamageDealt` DOUBLE NULL COMMENT '',
  `totalDamageDealtToChampions` DOUBLE NULL COMMENT '',
  `totalDamageTaken` DOUBLE NULL COMMENT '',
  `totalHeal` DOUBLE NULL COMMENT '',
  `totalPlayerScore` DOUBLE NULL COMMENT '',
  `totalScoreRank` DOUBLE NULL COMMENT '',
  `totalTimeCrowdControlDealt` DOUBLE NULL COMMENT '',
  `totalUnitsHealed` DOUBLE NULL COMMENT '',
  `towerKills` DOUBLE NULL COMMENT '',
  `tripleKills` DOUBLE NULL COMMENT '',
  `trueDamageDealt` DOUBLE NULL COMMENT '',
  `trueDamageDealtToChampions` DOUBLE NULL COMMENT '',
  `trueDamageTaken` DOUBLE NULL COMMENT '',
  `unrealKills` DOUBLE NULL COMMENT '',
  `visionWardsBoughtInGame` DOUBLE NULL COMMENT '',
  `wardsKilled` DOUBLE NULL COMMENT '',
  `wardsPlaced` DOUBLE NULL COMMENT '',
  `winner` TINYINT(1) NULL COMMENT '',
  `participantId` INT NULL COMMENT '',
  `matchId` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`ParticipantTimeline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`ParticipantTimeline` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`ParticipantTimeline` (
  `int` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tenToTwenty` DOUBLE NULL COMMENT '',
  `thirtyToEnd` DOUBLE NULL COMMENT '',
  `twentyToThirty` DOUBLE NULL COMMENT '',
  `zeroToTen` DOUBLE NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `lane` VARCHAR(45) NULL COMMENT '',
  `role` VARCHAR(45) NULL COMMENT '',
  `participantId` INT NULL COMMENT '',
  `matchId` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`int`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Item` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Item` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `item_id` INT NULL COMMENT '',
  `description` VARCHAR(1000) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `group_item` VARCHAR(45) NULL COMMENT '',
  `version` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Champion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Champion` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Champion` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `championId` INT NULL COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `keyChampion` VARCHAR(45) NULL COMMENT '',
  `version` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Dtw_Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Dtw_Item` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Dtw_Item` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `keyChampion` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `amount` INT NULL COMMENT '',
  `version` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Dtw_Champion11`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Dtw_Champion11` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Dtw_Champion11` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `win` INT NULL COMMENT '',
  `game` INT NULL COMMENT '',
  `winrate` DOUBLE NULL COMMENT '',
  `version` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Dtw_Champion14`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Dtw_Champion14` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Dtw_Champion14` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `win` INT NULL COMMENT '',
  `game` INT NULL COMMENT '',
  `winrate` DOUBLE NULL COMMENT '',
  `version` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Champion_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Champion_tags` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Champion_tags` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `championId` INT NULL COMMENT '',
  `tag` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Dtw_Champion_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Dtw_Champion_Role` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Dtw_Champion_Role` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `lane` VARCHAR(45) NULL COMMENT '',
  `amount` INT NULL COMMENT '',
  `version` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Dtw_Champion_Mode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Dtw_Champion_Mode` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Dtw_Champion_Mode` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `queueType` VARCHAR(45) NULL COMMENT '',
  `amount` VARCHAR(45) NULL COMMENT '',
  `version` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Dtw_Champion_KDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Dtw_Champion_KDA` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Dtw_Champion_KDA` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `kills` DOUBLE NULL COMMENT '',
  `deaths` DOUBLE NULL COMMENT '',
  `assists` DOUBLE NULL COMMENT '',
  `wardsPlaced` DOUBLE NULL COMMENT '',
  `version` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Dtw_item11`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Dtw_item11` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Dtw_item11` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `amount` DOUBLE NULL COMMENT '',
  `version` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Your_Database`.`Dtw_item14`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Your_Database`.`Dtw_item14` ;

CREATE TABLE IF NOT EXISTS `Your_Database`.`Dtw_item14` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `amount` DOUBLE NULL COMMENT '',
  `version` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
